version: "3.9"

services:
  backend:
    build: ./backend
    container_name: bug_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  frontend:
    build: ./frontend/front
    container_name: bug_frontend
    working_dir: /app
    volumes:
      - ./frontend/front:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

  mysql:
    image: mysql:8
    container_name: bug_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bug_defect
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: